//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://imtimo.vip/validate//Validate.ashx");
            request1.Method = "POST";
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request1.Headers.Add(new WebTestRequestHeader("UserName", "JS2APP"));
            request1.Headers.Add(new WebTestRequestHeader("UserPwd", "E1B55403653147648B61BD44C3057EDB"));
            request1.Headers.Add(new WebTestRequestHeader("MachineCode", "MachineCode"));
            request1.Headers.Add(new WebTestRequestHeader("Type", "Validate"));
            FormPostHttpBody request1Body = new FormPostHttpBody();
            request1.Body = request1Body;
            yield return request1;
            request1 = null;
        }
    }
}
